### ISSUE TITLE
runtime.connect should return Port

### ISSUE THREAD

**Issue by mckenfra** [stoically/webextensions-api-mock#1]
Hi,

I've added a pull request to https://github.com/mozilla/multi-account-containers But the pull request is behind the latest `master`, because when I rebase my pull request to the latest `master`, the tests fail. I can see that the latest `master` changes have migrated `multi-account-containers` to use `web-extensions-api-mock` for the test setup.

Unfortunately, my pull request has code that calls `runtime.connect`, and expects the returned object to be a `runtime.Port`. But I can see in https://github.com/stoically/webextensions-api-mock/blob/master/src/generated/types.d.ts that the `Runtime` interface maps the `connect` property to a simple `SinonStub` instead of a `Port` object. Also the `Port` object in the same file only has a single `name` property, whereas it should have `disconnect`, `postMessage`, `onDisconnect`, `onMessage`.

I'd be happy to try to figure out how to get this working, but I can't seem to get started with making changes and regenerating https://github.com/stoically/webextensions-api-mock/blob/master/src/generated/types.d.ts Can you let me know how to run the generation step?

Thanks!

Francis

**Comment by stoically** [comment]
Hey, the MAC recording feature is pretty cool!

So yeah, currently the implementation here is pretty dumb and doesn't build stubs for function return values that are actually types - it would have basically to respect the [`returns` property and resolve `$ref`s](https://github.com/stoically/webextensions-api-mock/blob/59d14a588fe71ec86b62a6c15be831c6d0edef79/src/generated/schema.json#L9821-L9824). Generating the schema and types should be as simple as running `npx ts-node src/bin.ts`.

However, I think implementing that would be no easy feat, so if you just want to get your tests working you could do the similar thing you did with the [old browser mock](https://github.com/mozilla/multi-account-containers/pull/1613/files#diff-a0b11712f3d0d0ead335cac0e0640e12R16-R18) and simply call `background.browser.runtime.connect.returns({...})` in before/beforeEach.

Hope that helps!

**Comment by mckenfra** [comment]
Thanks for the fast reply! Yes the recording feature works well, it was a bit tricky in places (e.g. working out how to "host" the popup in an iframe) but I'm pleased with the end result :-)

Thanks for the tip about the quick-fix to get the tests working again. I'll definitely try that for now, but I might also have a go at getting `Port` working in `webextensions-api-mock`. I was hoping it might be a quick fix, but as I dug deeper into `webextensions-api-mock` I realised there's a lot of stuff going on... so I may not get anywhere, but I'll give it shot...!

**Comment by mckenfra** [comment]
From my perspective this issue is now resolved with the latest merges to `master`. I.e. I can remove these lines from my MAC test script https://github.com/mozilla/multi-account-containers/blob/30a2601d35cc0d6aae1e0a681b69a0e6a995c751/test/helper.js#L22-L24 then point my `webextensions-api-mock` package to this latest version, and now my MAC tests run successfully! So I'll close this issue :-)
